version: '3.8'
services:
    db:
        container_name: hippo-db
        image: postgres:10.3
        restart: always
        environment:
            - POSTGRES_DB=hippo-db
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        volumes:
            - postgres:/var/lib/postgresql/data
        # ports:
            # - 5432:5432
        networks:
            - hippo-web
    api:
        container_name: hippo-api
        image: node:16-alpine
        restart: always
        build: ./api
        environment:
            - DATABASE_URL=$DATABASE_URL
        # ports:
            # - 3000:3000
        depends_on:
            - db
        links:
            - db
        networks:
            - hippo-web
    nginx:
        container_name: hippo-nginx
        build: ./.nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/log/nginx:/var/log/nginx
            - /var/www/html:/var/www/html
        restart: always
        depends_on:
            - api
        links:
            - api
            - db
        networks:
            - hippo-web
volumes:
    postgres:
networks:
    hippo-web:
        driver: bridge
