version: '3.8'
services:
  db:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_DB=hippo-db
      - POSTGRES_USER=hippo
      - POSTGRES_PASSWORD=Docker
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - hippo-web
  api:
    image: node:16-alpine
    restart: always
    build: ./api
    ports:
      - '3001:3000'
    depends_on:
      - db
    networks:
      - hippo-web
volumes:
  postgres:

networks:
  hippo-web:
    driver: bridge