version: '3.8'
services:
  db:
    container_name: hippo-db-dev
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_DB=hippo-db
      - POSTGRES_USER=hippo
      - POSTGRES_PASSWORD=Docker
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
networks:
  hippo-web:
    driver: bridge
