# this is used in docker-compose.prop.yaml
FROM nginx

WORKDIR /usr/share/nginx/html

# Remove default nginx configuration
RUN rm -rf /etc/nginx/sites-enabled/default

# Copy custom configuration file from the current directory
COPY ./ssl/certs/hippo-nginx-selfsigned.crt /etc/ssl/certs/
COPY ./ssl/private/hippo-nginx-selfsigned.key /etc/ssl/private/

COPY ./nginx.conf /etc/nginx/nginx.conf 

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]